# Generated by Django 3.0.3 on 2020-08-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0003_auto_20200806_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
