# Generated by Django 3.0.3 on 2020-09-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0006_auto_20200827_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
            ],
        ),
    ]
