# Generated by Django 3.0.3 on 2020-09-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0008_user_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_views',
            field=models.TextField(blank=True, null=True),
        ),
    ]
