# Generated by Django 3.1.6 on 2021-07-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0009_auto_20200903_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_views',
            field=models.TextField(default=0),
        ),
    ]
